export const INCREMENT_ITEM_IN_CART = 'INCREMENT_ITEM_IN_CART';
export const DECREMENT_ITEM_IN_CART = 'DECREMENT_ITEM_IN_CART';
export const SEARCH_VEGETABLES = 'SEARCH_VEGETABLES';
export const FILTER_CHANGE = 'FILTER_CHANGE';