export const VEGETABLE_ITEMS_FETCH = 'VEGETABLE_ITEMS_FETCH';
export const VEGETABLE_ITEMS_STATE_UPDATE = 'VEGETABLE_ITEMS_STATE_UPDATE';
export const VEGETABLE_ITEMS_API_UPDATE_FAILURE = 'VEGETABLE_ITEMS_API_UPDATE_FAILURE';
export const ITEMS_CART_UPDATE = 'ITEMS_CART_UPDATE';
export const CLEAR_CART_STATE_UPDATE = 'CLEAR_CART_STATE_UPDATE';