export const INCREMENT_ITEM_IN_CART = 'INCREMENT_ITEM_IN_CART';
export const DECREMENT_ITEM_IN_CART = 'DECREMENT_ITEM_IN_CART';
export const REMOVE_ITEM_FROM_CART = 'REMOVE_ITEM_FROM_CART';
export const CLEAR_CART = 'ClEAR_CART';
export const SEARCH_VEGETABLES = 'SEARCH_VEGETABLES';